version: "3"

services:
  db:
    image: mysql:8.0
    container_name: lesson_db
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lesson
    volumes:
      - lesson_data:/var/lib/mysql

volumes:
  lesson_data:
    driver: local